/**
 * Privacy Advisor Agent Types
 *
 * Type definitions for the LangChain-powered Privacy Advisor Agent
 * that provides intelligent, contextual privacy recommendations.
 *
 * @packageDocumentation
 */

import type { FullAnalysisResult, RiskLevel } from '../surveillance/types'

/**
 * Advisor message role
 */
export type AdvisorRole = 'user' | 'assistant' | 'system'

/**
 * Chat message for the advisor
 */
export interface AdvisorMessage {
  /** Message role */
  role: AdvisorRole
  /** Message content */
  content: string
  /** Timestamp */
  timestamp: number
}

/**
 * Advisor recommendation with priority and actionability
 */
export interface AdvisorRecommendation {
  /** Unique identifier */
  id: string
  /** Priority level (1 = highest) */
  priority: number
  /** Recommendation title */
  title: string
  /** Plain-English explanation */
  explanation: string
  /** Step-by-step action items */
  actions: string[]
  /** Expected privacy score improvement */
  expectedImprovement: number
  /** Difficulty level */
  difficulty: 'easy' | 'medium' | 'hard'
  /** Estimated time to implement */
  estimatedTime: string
  /** Whether SIP Protocol can automate this */
  canAutomate: boolean
}

/**
 * Privacy advisory report generated by the agent
 */
export interface PrivacyAdvisoryReport {
  /** Wallet address analyzed */
  walletAddress: string
  /** Current privacy score */
  currentScore: number
  /** Risk level assessment */
  riskLevel: RiskLevel
  /** Executive summary (2-3 sentences) */
  summary: string
  /** Prioritized recommendations */
  recommendations: AdvisorRecommendation[]
  /** Key risks explained in plain language */
  keyRisks: Array<{
    category: string
    description: string
    severity: RiskLevel
  }>
  /** SIP Protocol benefits if adopted */
  sipBenefits: {
    projectedScore: number
    improvement: number
    features: string[]
  }
  /** Report generation timestamp */
  generatedAt: number
}

/**
 * Advisor agent configuration
 */
export interface PrivacyAdvisorConfig {
  /** OpenAI API key */
  openaiApiKey: string
  /** Model to use (default: gpt-4o-mini for cost efficiency) */
  model?: 'gpt-4o-mini' | 'gpt-4o' | 'gpt-4-turbo'
  /** Temperature for responses (0-1, default: 0.3) */
  temperature?: number
  /** Maximum tokens per response (default: 1024) */
  maxTokens?: number
  /** Enable verbose logging */
  verbose?: boolean
}

/**
 * Analysis context passed to the advisor
 */
export interface AdvisoryContext {
  /** Full surveillance analysis result */
  analysisResult: FullAnalysisResult
  /** User's question or request (optional) */
  userQuery?: string
  /** Previous conversation messages */
  conversationHistory?: AdvisorMessage[]
  /** User preferences */
  preferences?: {
    /** Prioritize automation over manual steps */
    preferAutomation?: boolean
    /** Technical skill level */
    technicalLevel?: 'beginner' | 'intermediate' | 'advanced'
    /** Focus areas */
    focusAreas?: Array<'privacy' | 'compliance' | 'convenience'>
  }
}

/**
 * Advisor response
 */
export interface AdvisorResponse {
  /** Response message */
  message: string
  /** Generated report (if analysis was requested) */
  report?: PrivacyAdvisoryReport
  /** Suggested follow-up questions */
  suggestedQuestions?: string[]
  /** Token usage */
  usage?: {
    promptTokens: number
    completionTokens: number
    totalTokens: number
    estimatedCost: number
  }
}

/**
 * Tool execution result for LangChain tools
 */
export interface ToolResult<T = unknown> {
  /** Whether the tool executed successfully */
  success: boolean
  /** Result data */
  data?: T
  /** Error message if failed */
  error?: string
}

/**
 * Advisor status for React integration
 */
export type AdvisorStatus =
  | 'idle'
  | 'analyzing'
  | 'thinking'
  | 'responding'
  | 'error'

/**
 * Streaming callback for real-time responses
 */
export type StreamCallback = (chunk: string) => void
