// Provider
export { SIPProvider, type SIPProviderProps } from './providers/sip-provider'

// Hooks
export {
  useSIP,
  useStealthAddress,
  usePrivateSwap,
  useViewingKey,
} from './hooks'

// Components
export {
  // Generic components (NEAR-focused)
  PrivacyToggle,
  usePrivacyToggle,
  type PrivacyLevel,
  type PrivacyToggleProps,
  type GasEstimate,
  type PrivacyLevelInfo,
  StealthAddressDisplay,
  useStealthAddressDisplay,
  isValidStealthAddress,
  truncateAddress,
  NEAR_NETWORKS,
  type StealthAddressDisplayProps,
  type OwnershipStatus,
  type NetworkConfig,
  TransactionTracker,
  useTransactionTracker,
  type TransactionTrackerProps,
  type TransactionStatus,
  type PrivacyVerificationStatus,
  type TransactionActionType,
  type TransactionAction,
  type PrivacyVerification,
  type PrivacyTransaction,
  ViewingKeyManager,
  useViewingKeyManager,
  type ViewingKeyManagerProps,
  type ViewingKey,
  type ViewingKeyStatus,
  type ViewingKeyUsage,
  type KeyExportFormat,
  type KeyImportSource,
  // Ethereum-specific components (M18)
  EthereumPrivacyToggle,
  useEthereumPrivacyToggle,
  type EthereumPrivacyToggleProps,
  type EthereumPrivacyLevel,
  type EthereumNetworkId,
  type EthereumGasEstimate,
  type EthereumPrivacyLevelInfo,
  type NetworkGasConfig,
  EthereumTransactionTracker,
  useEthereumTransactionTracker,
  ETHEREUM_NETWORKS,
  getNetworkByChainId,
  type EthereumTransactionTrackerProps,
  type EthereumNetwork,
  EthereumViewingKeyManager,
  useEthereumViewingKey,
  type EthereumViewingKeyManagerProps,
  type EthereumViewingKey,
  EthereumStealthAddressDisplay,
  useEthereumStealthAddressDisplay,
  ETHEREUM_STEALTH_NETWORKS,
  isValidEthereumAddress,
  isValidEthereumStealthAddress,
  isValidEphemeralPublicKey,
  truncateEthereumAddress,
  type EthereumStealthAddressDisplayProps,
  type EthereumOwnershipStatus,
  type EthereumStealthNetworkId,
  type EthereumStealthNetworkConfig,
  TransactionHistory,
  useEthereumTransactionHistory,
  type TransactionHistoryProps,
  type PrivacyTransactionHistoryItem,
  type TransactionHistoryFilter,
  type TransactionHistorySort,
  // NEAR Transaction History (M17-NEAR-20)
  NEARTransactionHistoryView,
  type NEARTransactionHistoryViewProps,
} from './components'
